---
- name: working with secrets
  hosts: all
  vars_files:
    - mysecrets.yaml
  tasks:
    - name: getting details from secrets file
      command: echo "Database is {{db_name}} and password is [[db_pass}}"
